Document: cpg-network
Title: Debian cpg-network Manual
Author: <insert document author here>
Abstract: This manual describes what cpg-network is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cpg-network/cpg-network.sgml.gz

Format: postscript
Files: /usr/share/doc/cpg-network/cpg-network.ps.gz

Format: text
Files: /usr/share/doc/cpg-network/cpg-network.text.gz

Format: HTML
Index: /usr/share/doc/cpg-network/html/index.html
Files: /usr/share/doc/cpg-network/html/*.html
