#!/bin/sh

DEST="$(pwd)/_inst"

if [ -d "$DEST" ];
then
	rm -rf "$DEST"
fi

mkdir "$DEST"

(cd ../ && ./mingw-configure --prefix="$DEST" && make && make install) || exit 1

ZIP="$(pwd)/cpg-network-2.0.zip"
DEVZIP="$(pwd)/cpg-network-dev-2.0.zip"

curdir="$(pwd)"
cd "$DEST"

rm -f "$ZIP"
rm -f "$DEVZIP"

zip -r "$DEVZIP" include/* lib/*
zip -r "$ZIP" bin/* share/cpg-network-2.0 share/mime/packages/cpg.xml

cd "$curdir"
rm -rf "$DEST"
